### ISSUE TITLE
Storage.

### ISSUE THREAD

**Issue by talregev** [WebPlatformTest/HTML5test#338] opened 2014-05-23 19:26 UTC
Lots of time at storage chrome gets 26.(total 505)
and sometimes, it get 28 (total 507).
the different it here:
Objectstore ArrayBuffer support - 2 pt.
please check this test. it not constant for every load of the page.

**Comment by phistuck** [comment] 2014-06-07 14:38
I also noticed that. @NielsLeenheer - care to respond? Is this a browser issue, or a flaky test?

**Comment by phistuck** [comment] 2014-06-07 14:49
I just tested Internet Explorer 11 and it sometimes shows X for Blob and ArrayBuffer support and sometimes shows a check sign for both of them.
Either Chrome and Internet Explorer 11 have an issue here, or your test does (more likely?).

**Comment by NielsLeenheer** [comment] 2014-06-27 19:20
The test is almost identical to the Modernizr test:
https://github.com/Modernizr/Modernizr/blob/master/feature-detects/indexeddbblob.js

The test is actually pretty straightforward, but can fail at four different levels. I'm not sure at which level it fails in the cases you mention, but in any case this would appear to be a problem in the browser implementation and not the test itself. 

I personally cannot reproduce the issues you are seeing.

If the test fails, it can be caused on each of these moments:

1) The check for `window.indexedDB` and `'deleteDatabase' in indexedDB`

<pre>var indexedDB = window.indexedDB || window.webkitIndexedDB || window.mozIndexedDB || window.moz_indexedDB || window.oIndexedDB || window.msIndexedDB;
if (indexedDB && 'deleteDatabase' in indexedDB) {
   ...
}</pre>

2) The `onsuccess` event handler is not called after any existing database is deleted

<pre>indexedDB.deleteDatabase('html5test').onsuccess = function () {
   ...
}</pre>

3) The `onsucess` event handler is not called when we open the database again

<pre>var request = indexedDB.open('html5test', 1);
request.onsuccess = function() {
   ...
}</pre>

4) The actual creation of the objectStore and storing the data

<pre>try {
   db.transaction("store", "readwrite").objectStore("store").put(new Blob(), "key");
} catch (e) {
}</pre>
                    

If 1) fails we do not have indexedDB support. If 2) or 3) fails we most likely have a bug in the implementation. 4) means we do not support objectStorage.

**Comment by phistuck** [comment] 2014-06-27 22:32
IndexedDB support is present, only the Blob support is not when it is, in two browsers.

Maybe try to reverse the tests (first ArrayBuffer, then Blob, or the other way around)?
Maybe add some delay between the two tests (test IndexedDB, test other stuff, test ArrayBuffer, test other stuff, test Blob)?

This is not a consistent issue, though. Maybe report this to the browser vendors?

**Comment by NielsLeenheer** [comment] 2014-06-27 22:56
Could you run the following JavaScript code using the Webinspector in Chrome and F12 tools in IE?

<pre>var indexedDB = window.indexedDB || window.webkitIndexedDB || window.mozIndexedDB || window.moz_indexedDB || window.oIndexedDB || window.msIndexedDB;
if (indexedDB && 'deleteDatabase' in indexedDB) {
    try {
        indexedDB.deleteDatabase('html5test').onsuccess = function () {
            var request = indexedDB.open('html5test', 1);
            
            request.onupgradeneeded = function() {
                request.result.createObjectStore("store");
            };
            
            request.onsuccess = function() {
                var db = request.result;
                
                try {
                    db.transaction("store", "readwrite").objectStore("store").put(new Blob(), "key");
                    console.log('IndexedDB ObjectStore with Blob supported')
                } catch (e) {
                    console.log('IndexedDB ObjectStore with Blob not supported', e)
                }
                
                try {
                    db.transaction("store", "readwrite").objectStore("store").put(new ArrayBuffer(), "key");
                    console.log('IndexedDB ObjectStore with ArrayBuffer supported')
                } catch (e) {
                    console.log('IndexedDB ObjectStore with ArrayBuffer not supported', e)
                }
                
                db.close();
                indexedDB.deleteDatabase('html5test');
            };
        };
    } catch (e) {
        console.log(e);
    }
}</pre>

I'm curious what kind of exceptions are generated when the test fails.

**Comment by phistuck** [comment] 2014-06-28 07:45
I ran your code and both of the browsers (Chrome canary, that is, since Chrome 35 does not support it yet) passed successfully.

I tried html5test.com again in both of them -
- Internet Explorer 11 failed the first time and passed the rest.
- Chrome canary always fails.

When I try to inject console.log(c) into the catch code (I set a breakpoint, edit the code, save and continue running it), it does not show any console logging. That makes me suspect the update function might be doing something funky.

**Comment by NielsLeenheer** [comment] 2014-06-28 11:23
Hmm, okay. What perhaps happens is that in some cases the calls to IndexedDB take a while to complete. Usually this is no problem, but if it takes a couple of seconds, the whole testsuite may already be finished before the results for these test are updated.

I've modified the test on alpha.html5test.com to specifically wait for the async callbacks before stopping the testsuite and presenting the data.

Could you try on http://alpha.html5test.com?

**Comment by phistuck** [comment] 2014-06-28 11:35
Chrome passes every time!
Internet Explorer 11 (stable and developer channel) never shows the results, the throbber is shown indefinitely.

**Comment by NielsLeenheer** [comment] 2014-06-28 12:34
Chrome: good!

IE 11: strange, I'm still not seeing the same results. Mine is still showing the correct score, with both tests enabled. The fact that the throbber keeps running is an indication that the last async callback is never reached and the test is never marked as 'finished'.

I've updated alpha.html5test.com with some more error handling and I now log everything that happens to the console. Could you try again and if it fails let me know what the console log says?

**Comment by phistuck** [comment] 2014-06-28 13:16
Now it does not fail in the stable Internet Explorer 11. It keeps failing (shows the throbber indefinitely) in the developer channel, though. Nothing is logged.
The canary is still fine.

**Comment by NielsLeenheer** [comment] 2014-06-28 14:09
Weird, still works properly for me in both IE 11 and IE 11 Dev Channel. Which version of Windows are you using?

**Comment by phistuck** [comment] 2014-06-28 14:11
Windows 7 Enterprise SP 1 64 bit.

**Comment by NielsLeenheer** [comment] 2014-06-28 14:33
Works for me on Windows 7 SP1 64 bit.

Perhaps it is an cache issue for IE 11 Dev Channel. The latest version of the engine.js file should log something like this to the console:

<pre>IndexedDB: creating objectStore 
IndexedDB: database opened 
IndexedDB: objectStore with Blob passed 
IndexedDB: objectStore with ArrayBuffer passed </pre>

Could you open the F12 developer tools, disable the caches, go to the console and reload alpha.html5test.com?

**Comment by phistuck** [comment] 2014-06-28 14:50
The developer channel is fine now (I refreshed it using Control + F5 before. I have also used F12, which defaults to loading straight from the server, but it just kept showing the throbber). I am not sure what changed.

However... the stable Internet Explorer now shows the throbber indefinitely. I tried Control + F5, I tried using F12 so it always refreshes from the server. Nothing works. Throbber. Nothing in the console.

Chrome canary is fine as usual.

**Comment by NielsLeenheer** [comment] 2014-06-29 12:51
It looks like there is a bug in Internet Explorer 11.

In some situations it seems like the database that is created by the test cannot be deleted or opened. Access to the database is completely locked and any attempt to access it results in the onerror handler being called. 

Even a simple command like this in F12 console fails: 

<pre>window.indexedDB.open('html5test', 1).onerror = function() { console.log('error'); }</pre>

The onerror handler is called after 15 seconds or so.

The problem also seems temporary. It works for a number of times, then it becomes locked. It then fails for a number of times and suddenly starts working again.

**Comment by phistuck** [comment] 2014-06-29 16:29
Bummer. :( Can you report it at http://connect.microsoft.com/ie?

**Comment by NielsLeenheer** [comment] 2015-08-12 07:56
Microsoft Edge does not seem to suffer from this problem anymore.

**Closed as completed by NielsLeenheer** 2015-08-12 07:56 UTC
