### ISSUE TITLE
Nothing is shown in IE9+Win7

### ISSUE THREAD

**Issue by ghost** [WebPlatformTest/HTML5test#159] opened 2012-06-17 10:34 UTC
I have tried this page:
http://html5test.com/compare/browser/index.html

First of all - it is hard to get a list of browsers when you click on three big pluses - list just does not appear always - from time to time. Maybe it is loaded by AJAX and there is a connection issue? I don't know ;)
Another thing: when I choose a browser, nothing is shown in the capabilities table - it stays blank.

**Comment by NielsLeenheer** [comment] 2012-07-02 20:14
Duplicate of #145

**Closed as completed by NielsLeenheer** 2012-07-02 20:14 UTC
