### ISSUE TITLE
IE9 Platform Preview 3 supports H.264 and MPEG4 video but reports not to.

### ISSUE THREAD

**Issue by Gaurav0** [WebPlatformTest/HTML5test#47] opened 2010-06-24 20:16 UTC
IE9 Platform Preview 3 gets no "bonus points" for supporting H.264 and MPEG4 video, even though it supports it. This is because, like the iPhone, it returns "maybe" instead of "probably" in getPlayType(). I think all browser sniffing needs to be avoided and "maybe" accepted for all browsers.

**Comment by NielsLeenheer** [comment] 2010-06-24 20:26
"maybe" is not reliable enough to determine if a browser supports a codec. IE (and the iPhone) should simply return "probably" for codecs they support. The difference between the iPhone and IE in thus case is that the iPhone reliably reports "maybe" for codecs it support while IE also reports "maybe" for codecs it does not support. That makes a workaround for the iPhone possible, and for IE impossible.

**Comment by NielsLeenheer** [comment] 2010-08-24 08:02
Bug filed at Microsoft Connect and partially fixed in Preview 4

**Closed as completed by NielsLeenheer** 2010-08-24 08:02 UTC

**Comment by vnicolici** [comment] 2012-08-15 20:15
The issue is still not fixed for IE10 on Windows 8 Release Preview. It reports MPEG 4 is not supported, but it is.

**Comment by vnicolici** [comment] 2012-08-15 21:47
Nevermind, ignore my comment.
