### ISSUE TITLE
Need to add UC browser (U3 Engine)

### ISSUE THREAD

**Issue by youcansee** [WebPlatformTest/HTML5test#166] opened 2012-06-27 10:56 UTC
UC browser 8.5 scored 415 + 7 points with its own U3 Engine on HTC One X, Android 4.0.

UC has been concentrated on developing its own kernel of Mobile browsers for years. UC Browser “U3” is the Only “Kernel” Browser Engine Used by the Large Operators in China.

The latest U3 engine is the first browser kernel developed independently a brand new kernel that takes 3 years efforts to be done. It supports HTML5 well and provide HTML5 applications in its application center.

Here you can see some information about UC browser
http://www.ucweb.com/English/UCbrowser/patent.html

**Comment by NielsLeenheer** [comment] 2012-07-02 20:11
Duplicate of #153

**Closed as completed by NielsLeenheer** 2012-07-02 20:11 UTC
