### ISSUE TITLE
Odd IE9 numbers

### ISSUE THREAD

**Issue by msawczyn** [WebPlatformTest/HTML5test#240] opened 2013-01-29 11:21 UTC
In the browser comparison, IE9 is shown to have a score of 138(+5). Oddly enough, my test of IE9 shows a whopping 448(+13). Is something going horribly wrong?

![ie9html5](https://f.cloud.github.com/assets/1778442/106679/02965a22-6a06-11e2-91a8-2ab73dd67d4a.jpg)

**Comment by NielsLeenheer** [comment] 2013-02-02 16:12
Perhaps you installed Google Chrome frame and Chrome is doing the rendering instead of IE.

**Comment by Studio384** [comment] 2013-02-25 21:25
If I'm not wrong, a site needs to ask Chrome Frame to take over the rendering, why is the HTML5Test this doing anyway?

**Comment by mgol** [comment] 2013-03-30 13:30
Google Toolbar installs Chrome Frame automatically. The problem is, the html5test.com site has a meta tag: `<meta http-equiv="X-UA-Compatible" content="chrome=1">` which it obviously shouldn't have...

**Comment by NielsLeenheer** [comment] 2013-04-03 10:30
Will be fixed in the next minor update

**Closed as completed by NielsLeenheer** 2013-04-03 10:30 UTC
