### ISSUE TITLE
Test for width and height on image inputs is broken

### ISSUE THREAD

**Issue by bzbarsky** [WebPlatformTest/HTML5test#168] opened 2012-06-28 14:49 UTC
The source code looks like this, with irrelevant stuff elided:

  L = this.createInput("image");
  var ac="width" in L.field;
  L.field.setAttribute("width","100");
  S.setItem({id:"width",passed:ac&&L.field.offsetWidth==100,value:1});

This is assuming that setting the "width" attribute affects the height.  But for images with no src, browsers are allowed to make them non-replaced elements, in which case the width and height attributes have no effect.

You should be setting an actual src on the image input before testing the size.

**Comment by bzbarsky** [comment] 2012-06-28 14:50
Er, I meant: assuming that setting the "width" attribute affects the rendered width.  Which it won't for non-replaced inline images.

Alternately, you could style the input as block or inline-block if you want to make sure that the width and height are something interesting on it.

**Comment by NielsLeenheer** [comment] 2012-07-09 20:52
I've set the style of the field to 'inline-block' to force it affecting the rendered width and height.

Unrelated to the issue above, the test still fails on Gecko and Webkit, but due to that height and width are not exposed as content attributes. I've submitted the following bugs:
https://bugs.webkit.org/show_bug.cgi?id=90818
https://bugzilla.mozilla.org/show_bug.cgi?id=772207 (duplicate of 683855)

**Comment by bzbarsky** [comment] 2012-07-09 20:59
Thanks!  This isn't deployed to the html5test site yet, is it?

**Comment by NielsLeenheer** [comment] 2012-07-09 21:05
No, not yet. It is scheduled for the next version (currently at alpha.html5test.com). 

There are some more changes planned for the next week or two and once those changes are wrapped up I will deploy the new version hidden on the current site for a week or so, allowing me to gather the updated scores for each browser. Once I have enough data I will make the new test public, including the new scores.

**Comment by bzbarsky** [comment] 2012-07-09 21:21
Ah, thanks.  The alpha.html5test.com version looks good to me!

**Closed as completed** 2012-07-10 06:37 UTC
