### ISSUE TITLE
Do not test for string serialization of objects

### ISSUE THREAD

**Issue by arty-name** [WebPlatformTest/HTML5test#32] opened 2010-05-11 16:23 UTC
This is bad test:

```
element.toString() == '[object HTMLElement]';
```

You should directly test with `instanceof`:

```
(typeof HTMLElement != 'undefined') && (element instanceof HTMLElement)
```

Same should be applied to all elements support checks.

**Comment by NielsLeenheer** [comment] 2010-05-12 06:41
Duplicate of issue #24. Already fixed in master branch.

**Closed as completed by NielsLeenheer** 2010-05-12 06:41 UTC
