### ISSUE TITLE
Bug report of UC Browser

### ISSUE THREAD

**Issue by abaddon12** [WebPlatformTest/HTML5test#151] opened 2012-05-21 04:16 UTC
Dear Mr Niels Leenheer:

I'm Rocky Ding who is a Business Meneger of UC Browser. I have written two e-mails for you since two weeks ago. Acturally I would like to introduce our out-standing mobile Browser——UC Browser to you. And we alweys focus on html5 optimization of UC Browser. 

Currently we get a new breakthrough that UC Browser of Android 8.5 version reach 415 scores in Html5test.com. Maybe this is the highest scores so far in mobile browsers. (You can know about the detail from those two e-mails sent to niels@leenheer.nl)

We hope html5-test scores of UC Browser can be recorded in Html5test.com. Or could you just tell me how UC Browser can be recorded in Html5test.com?

Thank you for your attention. Look forward your reply.

**Comment by NielsLeenheer** [comment] 2012-07-02 20:12
Duplicate of #153

**Closed as completed by NielsLeenheer** 2012-07-02 20:12 UTC
